export default {
    Megathy: "مقاضي",

    // Menu

    Welcome: "مرحباً",
    Guest: "غير مشترك",
    Menu: "قائمة",
    Categories: "الأقسام",
    "Delivery Details": "تفاصيل التوصيل",
    "Order History": "الطلبات السابقة",
    "Scheduled Orders": "الطلبات المجدوله",
    "User Profile": "ملف العميل",
    "Suggest a Product": "اقترح منتج",
    "Terms of Services": "الشروط و الأحكام",
    "Contact us": "تواصل معنا",
    Logout: "خروج",

    // Login

    "Login with facebook": "سجل عن طريق حساب فيس بوك",
    OR: "او",
    "Email Id": "البريد الإلكتروني",
    Password: "كلمة المرور",
    Login: "تسجيل الدخول",
    "Forgot Password?": "نسيت كلمة المرور",
    "Continue as guest user": "تفضل كزائر",

    // Products

    "added to cart": "أضف مقاضيك إلى سلة التسوق",
    "removed from cart": "ارجع الغرض إلى الرف",
    Undo: "تراجع",
    "Search All Products": "البحث",
    "No Product Found": "نأسف لعدم العثور على الطلب",

    // Shopping Cart

    "Shopping Cart": "سلة التسوق",
    "Remove All": "حذف جميع المنتجات",
    //"Remove All": "إرجاع جميع المقاضي إلى الرفوف",
    "Your cart is empty": "سلة المقاضي فارغه",
    "Add Extra Notes...": "أضف ملاحظه",
    Schedule: "اطلب لاحقآ", // Asana Task 20170619
    //"Schedule": "جدوله",
    "Order Now": "اطلب الآن",
    "Send Your Order": "ارسل الطلب للتوصيل",

    // Delivery Details List

    "Deliver to this address": "وصل لهذا العنوان",
    "Select Address": "أختر العنوان",
    "Select Time": "اختر الوقت",
    ADD: "أضف",
    City: "المدينه",
    Area: "الحى",
    "Press here to locate your address": "اضغط هنا لتحديد موقعك",
    "Phone Number": "رقم الهاتف",
    Phone: "الهاتف",
    "Full Name": "الإسم كاملاً",
    "Location Notes": "ملحوظة بخصوص العنوان",
    "Order Summary": "ملخص الطلب",
    "Cash on delivery": "الدفع نقدا عند التسليم",
    "Cash on Delivery": "الدفع نقدا عند التسليم",
    "Pay with Cash": "الدفع نقدا",
    "Pay with Card": "الدفع بالبطاقة",
    CANCEL: "إلغاء",
    SEND: "أرسل",
    Location: "العنوان",
    "Add Location": "أضف عنوان",
    "Update Location": "حدث العنوان",
    "Select City": "إختر المدينة",
    "Select Area": "إختر الحي",
    Cancel: "الغاء",
    Done: "تم",
    Delete: "حذف",
    Edit: "تعديل",
    Next: "اختر وقت التوصيل",
    "Add New Address": "إضافة عنوان جديد",

    // Order History
    "IN PROCESS": "جاري التنفيذ",
    DELIVERED: "تم التوصيل",
    Active: "نشط",
    Inactive: "غير نشط",
    Placed: "تم إكتمال الطلب",
    Conformed: "مؤكد",
    Dispatched: "جاري التوصيل",
    Delivered: "تم التوصيل",

    // Order Detail

    "Order\nPlaced": "الطلب",
    "Items Confirmed": "تأكيد الطلبات",
    "Items Dispatched": "جاري التوصيل",
    "Items Delivered": "تم التوصيل",
    Payment: "الدفع",
    Items: "المقاضي",
    Add: "إضافة",
    "Select payment method": "اختر طريقة الدفع",
    "Payable Amount": "المبلغ المستحق الدفع",

    // Schedule Order History

    "Scheduled Order History": "الطلبات السابقه المجدوله",
    Date: "التاريخ",
    Time: "الوقت",
    Week: "الأسبوع",
    Days: "اليوم",

    // Schedule Order Setup

    "Setup Schedule": "جدول التوصيل",
    Submit: "ارسل الطلب",
    SUBMIT: "ارسل الطلب",
    Title: "تخصيص",
    Weekly: "أسبوعياً",
    Monthly: "شهرياً",
    "One time": "مره واحده",
    "On which week": "في اي اسبوع",
    First: "الأول",
    Second: "الثاني",
    Third: "الثالث",
    Fourth: "الرابع",
    "On which days": "في اي يوم",
    "Approximate delivery time": "وقت التوصيل التقريبي",
    "* Earliest delivery time 4h from now": "أقرب وقت للتوصيل أربع ساعات من الآن",
    "Scheduled Order Options": "خيارات جدولة التوصيل",
    "Cancel Order": "إلغاء الطلب",
    "Edit Schedule": "تغيير الجدول",
    "Active / Inactive": "نشط / غير نشط",
    "Thank you for your order, our employee will deliver your grocery and charge your credit card upon arrival":
        "نعتز بخدمتكم، سوف يقوم السائق بتوصيل طلبكم وإتمام عملية الدفع بالبطاقة البنكية",
    "Thank you for your order, our employee will deliver your grocery on time.":
        "نعتز بخدمتكم، سوف يقوم السائق بتوصيل طلبكم في الوقت المحدد.",
    Apply: " إضافه",
    "Coupon code": " أدخل رمز كوبون التخفيض",
    "Coupon Discount": "خصم الكوبون",
    "Coupon code cannot be blank": "رمز الكوبون فارغ",
    Feedback: "تحدث معنا",
    keyNoMessageTextFeedback: "إبدأ المحادثة مع فريق مقاضي. سوف يتم الرد بأسرع وقت",
    Messages: "الرسائل",
    Camera: "الكاميرا",
    Photos: "الصور",
    "Coupon is only valid till": "صلاحية الكوبون حتى",
    "so you will get discount till": "يستمر الخصم حتى",
    "Are you sure you want to apply this coupon?": "هل أنت متأكد من إستخدام الكوبون",
    "You have a message from App Admin": "لديك رسالة من مشرف التطبيقات",
    "Rate Us": "قيمنا",
    RateDialogDescription: "تقييم مقاضى إذا أحببت تطبيق مقاضي،  نرجوا التكرم بتقييم التطبيق. شكرًا لدعمكم",
    "Rate it": "قيمه",
    "Remind me later": "ذكرني لاحقا",
    "No thanks": "لا شكرا",
    "Send Confirmation Code": "إرسال رمز التأكيد",
    "Are you sure you want to stop phone verification process?":
        "هل أنت متأكد من أنك تريد إيقاف عملية التحقق من الهاتف؟",

    // User Profile

    "Choose your preferred language": "إختر اللغة المفضلة",
    "Edit User Profile": "تحديث ملف العميل",

    // Terms of Services

    "Coming Soon...": "قريباً",

    // Contact Us

    "How can we help you": "كيف نستطيع خدمتك",

    "You are already logged into another device. Please login again":
        "عميلنا العزيز، انت مسجل في جهاز اخر , الرجاء التسجيل مره اخرا",

    // Customer File 2

    "Background Location Access Disabled": "خاصية تحديد المواقع غير مفعله ",
    "In order to be notified about your order delivery status, please open this app's settings and set location access to 'Always’.":
        "للإستعلام عن حالة الطلب. الرجاء الدخول لقائمة الضبط وإختيار تحديد المواقع دائماً ",
    "Please wait…": "الرجاء الإنتظار... ",
    OK: "تم ",
    "Opps! something went wrong": "أوبس! حدث خطأ",
    "Error!": "خطأ",
    "Please check internet/wifi connection": "الرجاء التأكد من الإنترنت ",
    "Please login to continue. Do you want to login now?": "الرجاء تسجيل الدخول للمتابعه. هل تريد تسجيل الدخول الآن؟ ",
    No: "لا ",
    Yes: "نعم ",
    "Full Name cannot be blank": "الرجاء تسجيل الإسم كاملاً ",
    "Address cannot be blank": "الرجاء تسجيل العنوان ",
    "Earliest delivery time is 4 hours from now. Please select different time.":
        "أقرب وقت للتوصيل أربع ساعات من الآن. الرجاء إختيار وقت آخر ",
    "Earliest delivery time is 1 hour from now. Please select different time.":
        "أقرب وقت لخدمتكم هو بعد ساعه من الآن، الرجاء إختيار وقت آخر",

    "Are you sure want to remove all items from the cart?": "هل أنت متأكد أنك تريد مسح جميع الأغراض من عربة التسوق؟ ",
    "Are you sure want to cancel this order?": "هل أنت متأكد أنك تريد إلغاء الطلب؟ ",
    "Are you sure want to delete this address?": "هل أنت متأكد أنك تريد مسح هذا العنوان؟ ",
    "Please select at least one day for delivery": "الرجاء إختيار يوم التوصيل ",
    "days selected": "الأيام المختاره ",
    "Cart Amount": "قيمة الطلب", // New translation given in updates of 13 Jun, 2017

    Amount: "كمية",
    //"Cart Amount": "كمية العربه ",
    "Total Amount": "المبلغ المستحق",
    "Please select a time slot": "الرجاء إختيار وقت التوصيل ",
    "App Version: ": "إصدار التطبيق ",
    "Phone cannot be blank": "الرجاء إدخال رقم الهاتف ",
    "Old Password cannot be blank": "الرجاء إدخال كلمة المرور السابقه ",
    "New Password cannot be blank": "الرجاء إدخال كلمة المرور الجديده ",
    "Password and confirm password do not match": "كلمة المرور غير متطابقة ",
    "Thank you for contacting us. We will get back to you shortly": "شكراً لتواصلكم. سنعود إليكم عاجلاً ",
    "Invalid email id": "البريد الإلكتروني غير صحيح ",
    "Comment cannot be blank": "الرجاء كتابة ملحوظة ",
    "Thank you for your valuable suggestion": "شكراً لإقتراحك ",
    "Please enter at least one product name/description": "الرجاء إختيار منتج واحد على الأقل ",
    "Please select a City": "الرجاء إختيار المدينه ",
    "Please select an Area": "الرجاء إختيار المنطقه ",
    "Store changed successfully": "تم تغيير المتجر بنجاح ",
    "Login Failed: ": "الرجاء محاولة التسجيل مره أخرى ",
    "Password cannot be blank": "الرجاء إدخال كلمة المرور ",
    "Please register phone number first": "الرجاء تسجيل رقم الهاتف أولاً ",
    "Password must contain at least 5 characters": "كلمة المرور لابد من احتوائها على خمسة أحرف على الأقل ",
    "This number is already verified": "تم التحقق من هذا الرقم ",
    "Confirmation code is sent to phone number you have entered": "تم إرسال رمز التحقق إلى رقم الهاتف المدخل ",
    "Please enter phone number": "الرجاء إدخال رقم الهاتف ",
    "Your phone number registered successfully": "تم تسجيل رقم الهاتف بنجاح ",
    "Sorry! Confirmation code is invalid. Please enter valid code":
        "نأسف. رمز التحقق المدخل غير صحيح. الرجاء إدخال الرمز الصحيح ",
    "Please enter confirmation code": "الرجاء إدخال رمز التأكيد ",

    "Change Password": "تغيير كلمة المرور ",
    Remove: "حذف ",
    "Select delivery dates": "إختر تاريخ التوصيل ",
    "Selected time slots": "إختر وقت التوصيل ",
    "*Tap on a time slot to remove": "إضغط على وقت للحذف ",
    "No date selected to schedule": "الرجاء إختيار تاريخ للتوصيل ",
    Save: "حفظ ",
    "Select Time Slot": "اختر وقت التوصيل",
    "Select time slot for date": "الرجاء إختيار وقت ",
    "All booked slots": " كل الأوقات المحجوزه",
    "All available slots": "كل الأوقات المتوفرة ",
    "Some available slots": "بعض الأوقات المتوفرة ",

    // New Status changed as on 20180528
    Booked: "محجوز",
    Available: "متاح",
    Partial: "بعض الاوقات متاحه",

    Verification: "التحقق ",
    "Your number": "رقم الهاتف ",
    "Enter your phone number": "أدخل رقم الهاتف ",
    BACK: "العوده ",
    NEXT: "التالي ",
    Qty: "الكميه ", // Note: abbreviated form of Quantity.
    "Payment Mode": "طريقة السداد ",
    "SELECT STORE": "إختر المتجر ",
    "Change Store": "تغيير المتجر ",
    "Product Name / Description": "إسم المنتج / الوصف ",
    Description: "وصف",
    "This store is already selected. Please select another store":
        "السوبرماركت المختار  اختير سابقا، يمكنك اختيار متجر اخر",
    "Selected days": "الأيام المحددة",

    // Driver File 1

    "Open Settings": "الضبط ",
    "Sort By": "الترتيب حسب ",
    "Sort Orders By": "رتب الطلبات حسب ",
    "Customer Name": "إسم العميل ",
    "Order Time": "وقت التوصيل ",
    "Customer City": "مدينة العميل ",
    "Customer Area": "منطقة العميل ",
    "Please check internet/wifi connection.": "الرجاء التأكد من الإنترنت ",
    "Customer Location": "موقع العميل ",
    "Opps! Could not get path between your location and customer location": "خطأ في تحديد الموقع ",
    "Change Language": "تغيير اللغه ",
    Pending: "تحت المعالجة ",
    Accepted: "مقبول ",
    Completed: "منجز ",
    "Sign Up": "سجل ",
    "SELECT CITY": "إختر المدينه ",
    "SELECT AREA": "إختر المنطقه ",
    Message: "رساله ",

    // Remaining Words File

    "Enter confirmation code": "أدخل رمز التحقق ",
    "Confirmation code": "رمز التحقق ",
    Reset: "إعادة الضبط ",
    Accept: "قبول ",
    Decline: "رفض ",
    "Delivery Address": "عنوان التوصيل ",
    "Gross Amount": "المبلغ ",
    "Delivery Charges": "رسوم التوصيل ",
    "Time remaining to place this order (in minutes)": "الوقت المتبقي لإتمام الطلب ",
    "Are you sure want to update status to": "تأكيد تحديث الحاله إلى.. ",
    Update: "تحديث ",
    Exit: "ىخرج",
    "You need to update your app first!!": "تحتاج إلى تحديث التطبيق الخاص بك أولا !!",
    "Are you sure want to accept this order?": "تأكيد قبول الطلب ",
    "Are you sure want to decline this order?": "تأكيد رفض الطلب ",
    "In order to be notified about orders placed by customers, please open this app's settings and set location access to 'Always'":
        "لإعلامك عن الطلبات، إذهب إلى الإعدادات وتأكد من وضع تحديد الموقع إلى دائما ",
    "Are you sure want to remove this item from the cart?": "هل أنت متأكد من حذف الغرض من العربه ",
    "Store current time": "التوقيت في المتجر ",
    "Time Slots": "الجدول ",
    "Earliest delivery time is": "أقرب وقت للتوصيل ",
    "hour from now": "ساعة من الآن ",
    "hours from now": "ساعات من الآن ",
    "Please select different time": "الرجاء إختيار وقت آخر ",
    "Customer Notes": "ملحوظة العميل ",
    "Order Amount": "كمية الطلب ",
    "Select days ": "إختار الأيام ",
    "Update User profile": "تحديث ملف العميل ",
    "Old Password": "كلمة المرور السابقه ",
    "New Password": "كلمة المرور الجديده ",
    "Confirm Password": "تأكيد كلمة المرور ",
    Change: "تغيير ",
    "Are You sure want to cancel this order": "هل أنت متأكد من قرار إلغاء الطلب؟ ",
    "Order Details": "تفاصيل الطلب ",
    "Address List": "قائمة العناوين ",
    "No order Found": "لم يتم إيجاد الطلب ",
    Orders: "الطلبات ",
    "Update Time": "تحديث الوقت ",
    Cash: "نقداً ",
    "Debit/Credit Card": "بطاقه إئتمانيه ",
    "No data found": "لاتوجد بيانات",
    "Please locate your address": "الرجاء تحديد الموقع",
    "Phone No": "رقم الهاتف",
    Back: "رجوع",
    "Forgot Password": "نسيت كلمة السر",
    "Add Address": "حدد موقعك",

    "Address Map": "عنوان الخريطة",
    "Set Address": "حدد موقعك",
    "Type a message": "اكتب رسالة",
    Send: "إرسال",

    // Language File ASANA V5.0
    "Order Status": "حالة الطلب",
    "Order Placed": "تم إضافة الطلب",
    "View Order": "عرض الطلب",
    "Your order placed successfully": "تم إضافة الطلب بنجاح",
    "Your order items are confirmed": "تم تجميع الطلب",
    "Your order is ready to dispatch": "الطلب في الطريق إليك",
    "Your order is delivered at your place": "تم توصيل الطلب لعنوانك",
    "My Wallet": "المحفظة",
    "My Rewards Wallet": "محفظة نقاطي",
    "Paid for Order": "قيمة الطلب",
    "Payment Received": "تم إستلام المبلغ",
    "Wallet Balance": "محتوى المحفظة",
    All: "ملخص النقاط",
    Redeemed: "نقاط مستخدمه",
    Collected: "مجموع النقاط",
    "Redeem Points": "إستبدال النقاط",
    Address: "العنوان",
    "Time slot": "الوقت",
    Dismiss: "تم",
    "available points are": "النقاط المتوفرة",
    change: "تغيير",
    "Please select address": "الرجاء إختيار العنوان",
    "Points will remaining in wallet": "سوف تبقى النقاط في المحفظة",
    Discount: "خصم",
    "No wallet points available": "لا يوجد نقاط للإستبدال ",
    "Reward Points": "نقاط المكافئات",
    "The Reward Points used here will be redeemed in the first order of this schedule order. So please make sure to keep sufficient wallet balance at the time of your first delivery. Thank you.":
        "سيتم إحتساب نقاط المكافئات مع أول طلب مجدول. الرجاء التأكد من وجود نقاط كافيه في المحفظة لإحتسابها مع خالص الشكر والتقدير.",
    CLOSE: "إغلاق",

    "CALL ME": "اتصل بي",
    "Resend confirmation again": "ارسل رمز التأكيد مره اخرى",
    "If you change the city, all your selected time slots will be released. Are you sure you want to continue?":
        "اذا تم تغيير المدينة للعنوان، لن يتم حفظ وقت التوصيل للعنوان الاخر",
    "Didn’t receive Confirmation code? Please wait for 30 seconds and if you don’t receive it, then you can resend it or click on Call Me":
        "هل وصلك رمز التفعيل؟ اذا لم تستلم الرمز في ٣٠ ثانيه الرجاء اعادة الارسال او الضغط على اتصل بي",
    "Live Tracking": "تتبع طلبك عالخريطه",
};
