export default {
    Megathy: "Megathy",

    // Menu

    Welcome: "Welcome",
    Guest: "Guest",
    Menu: "Menu",
    Categories: "Categories",
    "Delivery Details": "Delivery Details",
    "Order History": "Order History",
    "Scheduled Orders": "Scheduled Orders",
    "User Profile": "User Profile",
    "Suggest a Product": "Suggest a Product",
    "Terms of Services": "Terms of Services",
    "Contact us": "Contact us", "Favourite" : "Favourite",
    Logout: "Logout",

    // Login

    "Login with facebook": "Login with facebook",
    OR: "OR",
    "Email Id": "Email Id",
    Password: "Password",
    Login: "Login",
    "Forgot Password?": "Forgot Password?",
    "Continue as guest user": "Continue as guest user",

    // Products

    "added to cart": "added to cart",
    "removed from cart": "removed from cart",
    Undo: "Undo",
    "Search All Products": "Search All Products",
    "No Product Found": "No Product Found",

    // Shopping Cart

    "Shopping Cart": "Shopping Cart",
    "Remove All": "Remove All",
    "Your cart is empty": "Your cart is empty",
    "Add Extra Notes...": "Add Extra Notes...",
    Schedule: "Schedule",
    "Order Now": "Order Now",
    "Send Your Order": "Send Your Order",
    "Selected days": "Selected days",

    // Delivery Details List
    "Deliver to this address": "Deliver to this address",
    "Select Address": "Select Address",
    "Select Time": "Select Time",
    ADD: "ADD",
    City: "City",
    Area: "Area",
    "Press here to locate your address": "Press here to locate your address",
    "Phone Number": "Phone Number",
    Phone: "Phone",
    "Full Name": "Full Name",
    "Location Notes": "Location Notes",
    "Order Summary": "Order Summary",
    "Cash on delivery": "Cash on delivery",
    "Cash on Delivery": "Cash on Delivery",
    "Pay with Cash": "Pay with Cash",
    "Pay with Card": "Pay with Card",
    CANCEL: "CANCEL",
    SEND: "SEND",
    Location: "Location",
    "Add Location": "Add Location",
    "Update Location": "Update Location",
    "Select City": "Select City",
    "Select Area": "Select Area",
    Cancel: "Cancel",
    Done: "Done",
    Delete: "Delete",
    Edit: "Edit",
    Next: "Next",
    "Add New Address": "Add New Address",

    // Order History
    "IN PROCESS": "IN PROCESS",
    DELIVERED: "DELIVERED",
    Active: "Active",
    Inactive: "Inactive",
    Placed: "Placed",
    Conformed: "Conformed",
    Dispatched: "Dispatched",
    Delivered: "Delivered",

    // Order Detail

    "Order\nPlaced": "Order\nPlaced",
    "Items Confirmed": "Items Confirmed",
    "Items Dispatched": "Items Dispatched",
    "Items Delivered": "Items Delivered",
    Payment: "Payment",
    Items: "Items",
    Add: "Add",
    "Select payment method": "Select payment method",
    "Payable Amount": "Payable Amount",

    // Schedule Order History

    "Scheduled Order History": "Scheduled Order History",
    Date: "Date",
    Time: "Time",
    Week: "Week",
    Days: "Days",

    // Schedule Order Setup

    "Setup Schedule": "Setup Schedule",
    Submit: "Submit",
    SUBMIT: "SUBMIT",
    Title: "Title",
    Weekly: "Weekly",
    Monthly: "Monthly",
    "One time": "One time",
    "On which week": "On which week",
    First: "First",
    Second: "Second",
    Third: "Third",
    Fourth: "Fourth",
    "On which days": "On which days",
    "Approximate delivery time": "Approximate delivery time",
    "* Earliest delivery time 4h from now": "* Earliest delivery time 4h from now",
    "Scheduled Order Options": "Scheduled Order Options",
    "Cancel Order": "Cancel Order",
    "Edit Schedule": "Edit Schedule",
    "Active / Inactive": "Active / Inactive",
    "Thank you for your order, our employee will deliver your grocery and charge your credit card upon arrival":
        "Thank you for your order, our employee will deliver your grocery and charge your credit card upon arrival",
    "Thank you for your order, our employee will deliver your grocery on time.":
        "Thank you for your order, our employee will deliver your grocery on time.",
    Apply: "Apply",
    "Coupon code": "Enter Coupon Code",
    "Coupon Discount": "Coupon Discount",
    "Coupon code cannot be blank": "Coupon code cannot be blank",
    Feedback: "Chat with us",
    keyNoMessageTextFeedback:
        "This is the start of your conversation with the Megathy team. We'll stay in touch to help you get the most out of your app. Feel free to leave a message about anything that's on your mind. We'll get back to your questions, suggestions or anything else as soon as we can.",
    Messages: "Messages",
    Camera: "Camera",
    Photos: "Photos",
    "Coupon is only valid till": "Coupon is only valid till",
    "so you will get discount till": "so you will get discount till",
    "Are you sure you want to apply this coupon?": "Are you sure you want to apply this coupon?",
    "You have a message from App Admin": "You have a message from App Admin",
    "Rate Us": "Rate Us",
    RateDialogDescription: "We are glad to serve you, please take a moment to rate us, Thanks for your Support",
    "Rate it": "Rate it",
    "Remind me later": "Remind me later",
    "No thanks": "No thanks",

    // User Profile

    "Choose your preferred language": "Choose your preferred language",
    "Edit User Profile": "Edit User Profile",

    // Terms of Services

    "Coming Soon...": "Coming Soon...",

    // Contact Us

    "How can we help you": "How can we help you",
    "You are already logged into another device. Please login again": "You are already logged into another device. Please login again",

    // Customer File 2

    "Background Location Access Disabled": "Background Location Access Disabled",
    "In order to be notified about your order delivery status, please open this app's settings and set location access to 'Always’.":
        "In order to be notified about your order delivery status, please open this app's settings and set location access to 'Always’.",
    "Please wait…": "Please wait…",
    OK: "OK",
    "Opps! something went wrong": "Opps! something went wrong",
    "Error!": "Error!",
    "Please check internet/wifi connection": "Please check internet/wifi connection",
    "Please login to continue. Do you want to login now?": "Please login to continue. Do you want to login now?",
    No: "No",
    Yes: "Yes",
    "Full Name cannot be blank": "Full Name cannot be blank",
    "Address cannot be blank": "Address cannot be blank",
    "Earliest delivery time is 4 hours from now. Please select different time.":
        "Earliest delivery time is 4 hours from now. Please select different time.",
    "Earliest delivery time is 1 hour from now. Please select different time.":
        "Earliest delivery time is 1 hour from now. Please select different time.",

    "Are you sure want to remove all items from the cart?": "Are you sure you want to remove all items from the cart?",
    "Are you sure want to cancel this order?": "Are you sure you want to cancel this order?",
    "Are you sure want to delete this address?": "Are you sure you want to delete this address?",
    "Please select at least one day for delivery": "Please select at least one day for delivery",
    "days selected": "days selected",
    Amount: "Amount",
    "Cart Amount": "Cart Amount",
    "Total Amount": "Total Amount",
    "Please select a time slot": "Please select a time slot",
    "App Version: ": "App Version: ",
    "Phone cannot be blank": "Phone cannot be blank",
    "Old Password cannot be blank": "Old Password cannot be blank",
    "New Password cannot be blank": "New Password cannot be blank",
    "Password and confirm password do not match": "Password and confirm password do not match",
    "Thank you for contacting us. We will get back to you shortly":
        "Thank you for contacting us. We will get back to you shortly",
    "Invalid email id": "Invalid email id",
    "Comment cannot be blank": "Comment cannot be blank",
    "Thank you for your valuable suggestion": "Thank you for your valuable suggestion",
    "Please enter at least one product name/description": "Please enter at least one product name/description",
    "Please select a City": "Please select a City",
    "Please select an Area": "Please select an Area",
    "Store changed successfully": "Store changed successfully",
    "Login Failed: ": "Login Failed: ",
    "Password cannot be blank": "Password cannot be blank",
    "Please register phone number first": "Please register phone number first",
    "Password must contain at least 5 characters": "Password must contain at least 5 characters",
    "This number is already verified": "This number is already verified",
    "Confirmation code is sent to phone number you have entered":
        "Confirmation code is sent to phone number you have entered",
    "Please enter phone number": "Please enter phone number",
    "Your phone number registered successfully": "Your phone number registered successfully",
    "Sorry! Confirmation code is invalid. Please enter valid code":
        "Sorry! Confirmation code is invalid. Please enter valid code",
    "Please enter confirmation code": "Please enter confirmation code",

    "Change Password": "Change Password",
    Remove: "Remove",
    "Select delivery dates": "Select delivery dates",
    "Selected time slots": "Selected time slots",
    "*Tap on a time slot to remove": "*Tap on a time slot to remove",
    "No date selected to schedule": "No date selected to schedule",
    Save: "Save",
    "Select Time Slot": "Select Time Slot",
    "Select time slot for date": "Select time slot for date",
    "All booked slots": "All booked slots",
    "All available slots": "All available slots",
    "Some available slots": "Some available slots",

    // New Status changed as on 20180528
    Booked: "Booked",
    Available: "Available",
    Partial: "Partial",

    Verification: "Verification",
    "Your number": "Your number",
    "Enter your phone number": "Enter your phone number",
    BACK: "BACK",
    NEXT: "NEXT",
    Qty: "Qty", // Note: abbreviated form of Quantity.
    "Payment Mode": "Payment Mode",
    "SELECT STORE": "SELECT STORE",
    "Change Store": "Change Store",
    "Product Name / Description": "Product Name / Description",
    Description: "Description",
    "This store is already selected. Please select another store":
        "This store is already selected. Please select another store",

    // Driver File 1

    "Open Settings": "Open Settings",
    "Sort By": "Sort By",
    "Sort Orders By": "Sort Orders By",
    "Customer Name": "Customer Name",
    "Order Time": "Order Time",
    "Customer City": "Customer City",
    "Customer Area": "Customer Area",
    "Please check internet/wifi connection.": "Please check internet/wifi connection.",
    "Customer Location": "Customer Location",
    "Opps! Could not get path between your location and customer location":
        "Opps! Could not get path between your location and customer location",
    "Change Language": "Change Language",
    Pending: "Pending",
    Accepted: "Accepted",
    Completed: "Completed",
    "Sign Up": "Sign Up",
    "SELECT CITY": "SELECT CITY",
    "SELECT AREA": "SELECT AREA",
    Message: "Message",

    // Remaining Words File

    "Enter confirmation code": "Enter confirmation code",
    "Confirmation code": "Confirmation code",
    Reset: "Reset",
    Accept: "Accept",
    Decline: "Decline",
    "Delivery Address": "Delivery Address",
    "Gross Amount": "Gross Amount",
    "Delivery Charges": "Delivery Charges",
    "Time remaining to place this order (in minutes)": "Time remaining to place this order (in minutes)",
    "Are you sure want to update status to": "Are you sure you want to update status to",
    Update: "Update",
    Exit: "Exit",
    "You need to update your app first!!": "You need to update your app first!!",
    "Are you sure want to accept this order?": "Are you sure you want to accept this order?",
    "Are you sure want to decline this order?": "Are you sure you want to decline this order?",
    "In order to be notified about orders placed by customers, please open this app's settings and set location access to 'Always'":
        "In order to be notified about orders placed by customers, please open this app's settings and set location access to 'Always'",
    "Are you sure want to remove this item from the cart?": "Are you sure you want to remove this item from the cart?",
    "Store current time": "Store current time",
    "Time Slots": "Time Slots",
    "Earliest delivery time is": "Earliest delivery time is",
    "hour from now": "hour from now",
    "hours from now": "hours from now",
    "Please select different time": "Please select different time",
    "Customer Notes": "Customer Notes",
    "Order Amount": "Order Amount",
    "Select days ": "Select days ",
    "Update User Profile": "Update User Profile",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "Confirm Password": "Confirm Password",
    Change: "Change",
    "Are You sure want to cancel this order": "Are You sure you want to cancel this order",
    "Order Details": "Order Details",
    "Address List": "Address List",
    "No order Found": "No order Found",
    Orders: "Orders",
    "Update Time": "Update Time",
    Cash: "Cash",
    "Debit/Credit Card": "Debit/Credit Card",
    "No data found": "No data found",
    "Please locate your address": "Please locate your address",
    "Phone No": "Phone No",
    Back: "Back",
    "Forgot Password": "Forgot Password",
    "Add Address": "Add Address",

    "Address Map": "Address Map",
    "Set Address": "Set Address",
    "Type a message": "Type a message",
    Send: "Send",

    // Language File ASANA V5.0
    "Order Status": "Order Status",
    "Order Placed": "Order Placed",
    "View Order": "View Order",
    "Your order placed successfully": "Your order placed successfully",
    "Your order items are confirmed": "We are collecting your items ",
    "Your order is ready to dispatch": "Your order is on the way",
    "Your order is delivered at your place": "Your order is delivered at your place",
    "My Wallet": "My Wallet",
    "My Rewards Wallet": "My Rewards Wallet",
    "Paid for Order": "Paid for Order",
    "Payment Received": "Payment Received",
    "Wallet Balance": "Wallet Balance",
    All: "All",
    Redeemed: "Redeemed",
    Collected: "Collected",
    "Redeem Points": "Redeem Points",
    Step1: "Step1",
    Step2: "Step2",
    Step3: "Step3",
    Address: "Address",
    "Time slot": "Time slot",
    Dismiss: "Dismiss",
    "available points are": "available points are",
    change: "change",
    "Please select address": "Please select address",
    "Points will remaining in wallet": "Points will remaining in wallet",
    Discount: "Discount",
    "No wallet points available": "No wallet points available",
    "Reward Points": "Reward Points",
    "The Reward Points used here will be redeemed in the first order of this schedule order. So please make sure to keep sufficient wallet balance at the time of your first delivery. Thank you.":
        "The Reward Points used here will be redeemed in the first order of this schedule order. So please make sure to keep sufficient wallet balance at the time of your first delivery. Thank you.",
    CLOSE: "CLOSE",

    "CALL ME": "CALL ME",
    "Resend confirmation again": "Resend confirmation again",
    "Didn’t receive Confirmation code? Please wait for 30 seconds and if you don’t receive it, then you can resend it or click on Call Me":
        "Didn’t receive Confirmation code? Please wait for 30 seconds and if you don’t receive it, then you can resend it or click on Call Me",
    "Live Tracking": "Live Tracking",
    "Send Confirmation Code": "Send Confirmation Code",
    "Are you sure you want to stop phone verification process?":
        "Are you sure you want to stop phone verification process?",
};
